defaults: &defaults
  working_directory: ~/tamnun-ml
  steps:
    - run:
        name: Avoid hosts unknown for github
        command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    - checkout
    - run:
        name: Create combine dependencies and python version file - as cache key checksum
        command: |
          cat setup.py > cache_key.txt
          echo $PYTHON_VERSION >> cache_key.txt
    - run:
        name: Create virtualenv
        command: |
          virtualenv venv
    - restore_cache:
        key: deps-{{ checksum "cache_key.txt" }}
    - run:
        name: Install dependencies
        command: |
          . venv/bin/activate
          pip install --progress-bar off -e .
    - run:
        name: Run general pytest
        command: |
          . venv/bin/activate
          py.test tests

version: 2
jobs:
  build-python3:
    docker:
      - image: circleci/python:3.7.2
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
      - build-python3